### PR TITLE
Feat: adding some style and correct the text style

### PR DESCRIPTION
**Pull request by abhishekraoas**

### CODE REVIEW

**Review by Mohasin-Haque — CHANGES_REQUESTED** [review]
Firstly, please host your branch, then format the code using prettier or beautify and also I would like a small change in Index.html code. Please put "*" in place of "X" in multiply button. Rest of the things are looking fine. but please do the above things so I can review easily. 
Thank you!!

**Comment by abhishekraoas** [comment]
I do everything correct and you can see again

**Review by Mohasin-Haque — APPROVED** [review]
Thanks for changes !!

**Comment by Mohasin-Haque** [comment]
Thanks for your contribution.. You can checkout some more issues in my GitHub. I will happy to work with you.😊😊

**Pull request merged**
